### ISSUE TITLE
Files missing after installing package

### ISSUE THREAD

**Issue by maan-maker** [Kentico/kontent-webhook-helper-js#23]
### Brief bug description

Files missing after installing package. 

### Repro steps

1. Run `npm i @kontent-ai/webhook-helper`
2. Check folder `../node_modules/@kontent-ai/webhook-helper`
3. Folder does not include all files, only LICENSE.md, package.json & README.md

### Expected behavior

Expecting the rest of the files when running install.

### Test environment

 - Platform/OS: Mac OS BigSur 11.6.5

### Additional context

The tgz archive in the `package.lock.json` file contains the issue.
```
{
  "name": "kontent-ai-test",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@kontent-ai/webhook-helper": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/@kontent-ai/webhook-helper/-/webhook-helper-2.0.0.tgz",
      "integrity": "sha512-BFBn7e7cuY3mYC0bmcP4dqCbBlA226FMiFQ7C2YXd50ymzb8AKWWIN6pcoLTc/Vn6GviQl2fR36Pm4SQN3JKxw=="
    }
  }
}
```

FYI, can still use the old library with no issues by running `npm i @kentico/kontent-webhook-helper`

### Screenshots

![image](https://user-images.githubusercontent.com/106128756/179880615-2041e72f-9d53-410d-9a58-9193348dfde0.png)

**Comment by Enngage** [comment]
@maan-maker thank you for submitting this! I've forgotten to update the `.npmignore`. Could you please try updating to `2.0.1` and let me know if that works well for you?

**Comment by maan-maker** [comment]
@Enngage thanks for that. Can confirm that its working now after updating 👍
